### ISSUE TITLE
Delete Bucket Glitch

### ISSUE THREAD

**Issue by ItsTempestuous** [gloridifice/WaterSource#13]
Buckets of purified water, soul water, and coconut milk stack and then when you place them down it turns into 1 empty bucket.

**Comment by ghost** [comment]
i was able to fix this by changing the max stack of the buckets to 1 (using kubejs). it seems the issue is derived from the interaction code expectations of it actually being 1 like with others buckets (vanilla and most modded buckets with fluid or fishes). 
also, i have noticed the same deleting behavior on another mod which has some filled bucket with max stack of 64 too, which i fixed the same way.
